config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :class_rosters do
    member do 
      get :toggle_status
    end 
  end

  resources :posts do 
    member do 
      get :toggle_status
      get :toggle_timeslot
    end 
  end 
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
resources 'users' do
  resources 'posts'
end 

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'schedule', to: 'pages#schedule'
  get 'payments', to: 'pages#payments'

  resources :blogs do 
    member do 
      get :toggle_status
    end 
  end

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :deposit, only: [:new, :create]
  get 'thank_you', to: 'deposit#thank_you', as: 'thank_you'
  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1 }
    extend FriendlyId
    friendly_id :title, use:  :slugged

    validates_presence_of :title, :body

    belongs_to :topic
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:admin)
    @blogs = Blog.all
  else
    @blogs = Blog.published
  end
    @page_title = "The Learning Center Blog"
  end


  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :toggle_status)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blogcard.html.erb
<div class="card green lighten-2">
    <div class="row">
                <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.title, blog_path(blog) %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to(edit_blog_path(blog), :id => :blog, class: "btn-floating yellow darken-1") do %>
              <i class='material-icons'>edit</i><% end %><td>
        <td><%= link_to(blog_path(blog), :id => :blog, class: "btn-floating green") do %><i class="material-icons">assignment_return</i><% end %><td>

  <td><%= link_to(blog, :method=>:delete, class: "btn-floating red", data: { confirm: 'Are you sure?' }) do %>
              <i class='material-icons'>delete</i><% end %><td>
      </tr>
    <% end %>
  </tbody>
</table>
    
    </div>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "TLC Blogs") %>
    <% end %>
      <% end %>
      

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag "_header.png" %>

<h1>Blogs</h1>

<%= render 'blogcard' %>

<br>

<a class="btn-floating btn-large waves-effect waves-light red" href="/blogs/new"><i class="material-icons">class</i></a>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>