config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :class_rosters do
    member do 
      get :toggle_status
    end 
  end

  resources :posts do 
    member do 
      get :toggle_status
      get :toggle_timeslot
    end 
  end 
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
resources 'users' do
  resources 'posts'
end 

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'schedule', to: 'pages#schedule'
  get 'payments', to: 'pages#payments'

  resources :blogs do 
    member do 
      get :toggle_status
    end 
  end

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :deposit, only: [:new, :create]
  get 'thank_you', to: 'deposit#thank_you', as: 'thank_you'
  root to: 'pages#home'
end

app/views/shared/_about_card.html.erb
<div class="card-panel amber lighten-2">
  <div class="row">
   <div class="divider"></div>
  <div class="section">
    <h3>Betsy Montoya</h3>
  </div>  
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header deep-purple"><i class="material-icons">filter_drama</i>Master’s Degree in Family Studies and Human Development</div>
          <div class="collapsible-body"><span>
        <p>Utah State University</p>
        <p>Classes taught by Elizabeth Montoya, or Miss Betsy, a Master’s Degree in Family Studies and Human Development. She has been teaching here for 5+ years and has had very successful student progression. She loves her position and her students very much!</p>
      </span></div>
        </li>
        <li>
          <div class="collapsible-header blue"><i class="material-icons">place</i>Growing Up</div>
          <div class="collapsible-body"><span><p>Betsy grew up in Grand Junction, Colorado. She comes from a family of four children and is the youngest. One of her fondest memories is of the playschool that she attended as a child and has always wanted to become a teacher.</p>
    </span></div>
        </li>
        <li>
          <div class="collapsible-header teal"><i class="material-icons">whatshot</i>Career</div>
          <div class="collapsible-body"><span><p>Betsy and her family moved to Vernal, Utah where Betsy was able to complete her Bachelor’s Degree with Honors and finally open her own preschool. In 2006, Betsy and her family relocated to Santaquin because of a job transfer for her husband. Rod works for the State of Utah as a Network Specialist.  Betsy has four children, all boys, ages 22, 20, 16 and 10. Miss Betsy completed her Master’s Degree in 2010 from Utah State University.</p>
    </span></div>
        </li>
        <li>
          <div class="collapsible-header blue"><i class="material-icons">account_circle</i>Personal Life</div>
          <div class="collapsible-body"><span><p>After graduating from high school, she went to Ricks College and completed her Associate Degree. She had met and married her husband within the first year at Ricks and had her first child just after graduation. She and her husband moved to Salt Lake City and then to Layton, Utah. This is where her first child started preschool and Betsy realized while helping in his class that she wanted to teach preschool instead of elementary school. She taught for a time for Davis School District in their preschool program. </p>
    </span></div>
        </li>
      </ul>
  </div>
</div>

  <script>$(document).ready(function(){
    $('.collapsible').collapsible();
  });</script>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
    <%= js add_gritter(flash[:alert], title: "TLC Preschool", image: "success", time: 1000) %>
<% elsif flash[:error] %>
    <%= js add_gritter(flash[:error], title: "TLC Preschool", image: "error", time: 1000) %>
<% else %>
        <%= js add_gritter(flash[:notice], title: "TLC Preschool", image: "success", time: 1000) %>
<% end %>

app/views/shared/_class_roster_card.html.erb
<div class="card amber accent-3">
    <div class="row">
        <h1>Daily Schedules</h1>

        <table>
        <thead>
        <tr>
            <th>Class</th>
            <th>Session</th>
            <th>Schedule</th>
            <th>Headcount</th>
            <th>Students</th>
            <th colspan="5"></th>
        </tr>
        </thead>

        <tbody>
        <% @class_rosters.each do |class_roster| if logged_in?(:admin) %>
        <% end %>
            <tr>
            <td><%= class_roster.title %></td>
            <td><%= link_to class_roster.status, toggle_status_class_roster_path(class_roster) %></td>
            <td><%= class_roster.subtitle %></td>
            <td><%= class_roster.count %></td>
            <td><%= class_roster.description %></td>
            <td><%= link_to(edit_class_roster_path(class_roster), :id => :class_roster, class: "btn-floating yellow darken-1") do %>
                    <i class='material-icons'>edit</i><% end %></td>
            <td><%= link_to(class_roster_path(class_roster), :id => :class_roster, class: "btn-floating green") do %><i class="material-icons">assignment_return</i><% end %></td>
            <td><%= link_to 'Destroy', class_roster, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:admin) %></td>
            </tr>
            
        <% end %>
        </tbody>
        </table>


    </div>
</div>

app/views/shared/_focus_card.html.erb
<div class="card-panel amber lighten-2">
  <div class="row">
    <div class="divider"></div>
      <div class="section">
        <h5>Children receive one on one attention!</h5>
        <p>Each child is an individual who is different from anyone else and learns differently, too!
        Free play time. Children learn by playing and we strive to make this work of learning and playing fun! Your child’s time at TLC is as developmentally productive as possible!
        An emphasis is placed on literacy and math skills. We learn a new letter each week and do fun activities to help us learn skills for reading and writing. We also emphasize skills such as rhyming, patterning, sorting, opposites and large and fine motor skills.</p>
      </div>
      <div class="divider"></div>
        <div class="section">
          <h6>Creativity and originality are highly encouraged!</h6>
          <p>I cannot stress enough the importance of allowing children to create original artwork. Creativity helps children be flexible in our changing world.</p>
        </div>
      <div class="divider"></div>
        <div class="section">
          <h6>Parental involvement is encouraged as well.</h6>
          <p>Parents are a child’s first and most important teachers! It is important to connect home and school. My policy is “open door” and I welcome parents in my classroom.</p>
        </div>
      <div class="divider"></div>
        <div class="section">
          <h6>Community partnership with Seasons of Santaquin care center-</h6>
          <p>about once a month we visit residents at the care center to enjoy mutually beneficial interactions of multi-generational friendships.</p>
        </div>
      </div>
    </div>

app/views/shared/_footer.html.erb
<footer class="page-footer amber">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="grey-text"><blockquote><%= image_tag '_header.png' %><br> (TLC)Preschool</h5></blockquote>
                <p class="grey-text text-lighten-4">You’ll LOVE the difference TLC can make!</p>
              </div>
              <div class="col l2 offset-l4 s12">
                <h5 class="grey-text">Quick links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-1" href="/class_rosters">Classes</a></li>
                  <li><a class="grey-text text-lighten-1" href="/posts">Register</a></li>
                  <li><a class="grey-text text-lighten-1" href="/blogs">Blogs</a></li>
                  <li><a class="grey-text text-lighten-1" href="/portfolios">Portfolios</a></li>
                  <li><a class="grey-text text-lighten-1" href="/charges/new">Tuition</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
             2017 The Learning Center © | Owned by Elizabeth Montoya | Site created and maintained by, Jordan <a href="http://www.github.com/jmontoya811"><%= image_tag "github1.png", width: 35, height: 30, alt: "footer image", class: "footer-img" %>
  
</a>
            <a class="grey-text text-lighten-4 right" href="#!">Top</a>
            </div>
          </div>
        </footer>

app/views/shared/_home_card.html.erb
<div class="card amber accent-3">
  <div class="row">
    <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src=" ">
    </div>
    <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">
            <blockquote>Find a a class, click to the right for schedules and availability</blockquote><i class="material-icons right">chevron_left</i></span>
            <hr>
      <div class="col s3">
        <p><%= link_to "Registration", posts_path %></p>
        <p><a class="btn-floating btn-large waves-effect waves-light red" href="/posts/new"><i class="material-icons">class</i></a>
        </p>
      </div>
      <div class="col s3">
        <p><%= link_to "Class of 2018", class_rosters_path %></p>
        <p><a class="btn-floating btn-large waves-effect waves-light cyan darken-3" href="/class_rosters/new"><i class="material-icons">description</i></a>
        </p>
      </div>
      <div class="col s3">
        <p><%= link_to "Payments", payments_path %></p>
        <p><a class="btn-floating btn-large waves-effect waves-light deep-orange" href="/payments"><i class="material-icons">account_balance</i></a>
        </p>
      </div>
    </div>
  </div>
  <div class="card-reveal amber">
      <span class="card-title grey-text text-darken-1"><blockquote>Schedule</blockquote><i class="material-icons right">close</i></span>
      <p>Classes are held Every Tuesday and Thursday, Morning Class: 9:15 AM to 11:45 PM, Afternoon Class: 12:30 PM to 3:00 PM</p>
      <p>Monthly tuition is $65.00, to reserve a students spot a 1 time materials fee/deposit of $50.00 is also required.</p>
      <blockquote><h4>Class Capacity: 12</h4></blockquote>
      <hr>

        <div class="container">
          <div class="skills">
              <% @skills.each do |skill| %>
            <div class="skill"><%= skill.title %><p>Class Capacity: <%= skill.percent_utilized %>%</p>
              <div class="progress">
                <div class="determinate" role="progress" aria-valuenow="<%= skill.percent_utilized %>" aria-valuemax="100" style="width: <%= skill.percent_utilized %>%">
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>


<div class="card amber accent-2">
  <div class="row">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">Explore curriculum<i class="material-icons right">more_vert</i></span>
    <div class="col s3">
      <p>Blogs</p>
      <p><a class="btn-floating btn-large waves-effect waves-light purple" href="/blogs"><i class="material-icons">add_box</i></a>
      </p>
    </div>
    <div class="col s3">
        <p><%= link_to "Schedules", schedule_path %></p>
        <p><a class="btn-floating btn-large waves-effect waves-light blue accent-2" href="/schedule"><i class="material-icons">schedule</i></a>
        </p>
      </div>
    <div class="col s3">
      <p>Portfolios</p>
      <p><a class="btn-floating btn-large waves-effect waves-light amber darken-3" href="/portfolios"><i class="material-icons">brush</i></a>
      </p>
    </div>
    </div>
  </div>
  <div class="card-reveal amber">
      <span class="card-title grey-text text-darken-4">Yearly theme: <i class="material-icons right">close</i></span>
      <blockquote>This year our theme is Dr. Seuss and we will have an amazing year!</blockquote>
      <p>Here is some more information about the teacher and her contact info.</p>
      <%= link_to "About the teacher", about_path %> | <%= link_to "Contact The Learning Center", contact_path %>
      
<blockquote><h5>Educational focus points, Rules, Healthy Snacks and Parent Helpers</h5></blockquote>
<blockquote><h6>Ways we learn</h6></blockquote>
<p>Literacy: Literacy is very important for preschoolers! Instead of “learning how to read” we lay the foundation for learning how to read by learning letters, sounds, rhymes, songs, playing games, practicing coordination and reading books together. You can also promote this at home by reading to your child every day! I will send home a reading log and if you read with your child each day, fill out the log and bring it back, your child will get a book each month!</p>
<p>Environmental print: Some months we will have an environmental print item that I will ask you to send with your child. We will do songs or activities with each one. Watch the calendar for these!</p>
<p>Play: Young children learn through play! Play is a very important part of childhood and preschool is the last opportunity your child will have to play for an adequate time in school. It is a very important part of my curriculum. </p>
<p>Discipline: Each child is expected to follow the basic rules of preschool: being a friend, listening, sharing, cleaning up and following directions. We practice these a lot in preschool. I use positive discipline strategies by setting high expectation paired with high levels of praise. If a child’s behavior is an excessive problem in the classroom, I will discuss the issues with parents and if the problem continues, the child will be dismissed from preschool.</p>
<blockquote><h6>Rules and expectations</h6></blockquote>
<p>Backpacks: Your child works hard on art projects, etc. in class and these will not fit into a “mini” backpack. Please send your child with a regular backpack or an open top bag for their papers.</p>
<p>Dress: Preschool can be kind of messy, so I recommend that you NOT send your child in their best clothes. We paint and do all sorts of projects, most of which use washable materials, but some do not. We try to stay clean but, sometimes, stains just happen!</p>
<p>Illness: Because this is probably your child’s first experience outside of home, you may find that they get sick more easily. I do everything I possibly can to prevent this, but the fact is that kids spread germs and illness. We wash hands and Clorox wipe surfaces often. If your child is ill, please keep them home. Help them get used to washing their hands often and coughing or sneezing into their sleeve. If they contract a contagious disease such as the chicken pox or strep throat, please let me know so I can inform other parents.</p>
<blockquote><h6>Parent Participation!</h6></blockquote>
<p>Class Help: I offer tuition credit for class helpers! If you come once, you may take off $5, if you come in twice, you may take off $10 from the next month’s tuition. You may stay the whole preschool time, or you may come for the last half of preschool (This is 10:30-11:45 or 1:45-3:00). And my door is always open!</p>
<p>Field trips: We take several field trips during the year and I must have parent helpers/drivers. There will be a sign-up sheet at the front door for field trip helpers before each trip. Some field trips are free, others will be $1- 3.00 and I make up the difference.</p>
<p>Snacks: You will be asked to help out with snack regularly throughout the year. Children love when it is their turn. This does not have to be fancy. Simple is better. Some ideas might be: apple slices, crackers & cheese, pretzels, granola bars, frozen Gogurt, etc. Please avoid cupcakes or really sugary snacks. A drink is optional but not necessary as we always have water!</p>
<p>VIP: Each child will have their turn to be our “Horton’s Hero”. I will send a note home letting you know when it is your child’s turn!</p>
<p>Calendars: I will send home a bi-monthly calendar that lets you know what we will be learning about each day, when there is no preschool because of Holidays, when there are field trips and when your child has snack. Put them somewhere handy as a reference and if you misplace it, I always have extras! I also email calendars and will ask for your email at open house.</p>
<p>Drop-off/pick-up: Please be prompt in dropping off and picking up your child. With two classes, I would like to have lunch in between. I also have obligations after school. I will wait downstairs for children to come in and we will come outside when preschool is finished.</p>
<p>My dog: I have a dog named Bella. She is friendly but she barks. She will be in her kennel during preschool hours but you will still hear her barking!</p>
<p>If you have any questions, please let me know!</p>
<p>Miss Betsy      801- 754-1399,  cell 385-208-3085</p>

  </div>
</div>

app/views/shared/_home_carousel.html.erb
<div class="carousel carousel-slider">
    <a class="carousel-item" ><%= image_tag "_header.png" %><%= image_tag "Betsy_Montoyas_School.png" %></a>
    <a class="carousel-item" ><%= image_tag "learntoplay.png" %></a>
    <a class="carousel-item" ><%= image_tag "kidscook.png" %></a>
    <a class="carousel-item" ><%= image_tag "Playtime.png" %></a>
  </div>

  <script>
  $('.carousel.carousel-slider').carousel({fullWidth: false});
  </script>

app/views/shared/_nav.html.erb
<nav>
    <div class="nav-wrapper amber">
    <a class="btn btn-floating btn-large pulse deep-purple"><i class="material-icons">school</i></a> |
      <a href="/" class="brand-logo pulse"><%= image_tag "TLC.png", width: 70, height: 70, alt: "profile image", class: "profile-img" %><%= image_tag "_header.png", width: 300, height: 75 %></a>
      <ul class="navbar-custom">
        <li><%= nav_helper 'nav-link', 'span' %></li>
        <li><%= login_helper %></li>
      </ul>
    </div>
  </div>
  </nav>

app/views/shared/_slider.html.erb
<div class="slider">
    <ul class="slides">
      <li>
        <%= image_tag "Betsy_Montoyas_School.png" %>
        <div class="black-text caption left-align">
          <h2>The Learning Center!</h2>
          <h5 class="green-text text-lighten-3">You'll Love the difference TLC can make!</h5>
        </div>
      </li>
      <li>
         <%= image_tag "learntoplay.png" %>
        <div class="black-text caption left-align">
          <h2>Daily Playtime</h2>
          <h5 class="green-text text-lighten-3">We teach the children social skills and how to have fun!</h5>
        </div>
      </li>
      <li>
         <%= image_tag "kidscook.png" %>
        <div class="black-text caption right-align">
          <h3>Education through experience!</h3>
          <h5 class="green-text text-lighten-3">We have a variety of activites and field trips we experience!</h5>
        </div>
      </li>
      <li>
         <%= image_tag "Playtime.png" %>
        <div class="caption center-align">
          <h2>Parent Participation</h2>
          <h5 class="green-text text-lighten-3">Parents are always encouraged to help and contribute!</h5>
        </div>
      </li>
    </ul>
  </div>

  <script>
  $(document).ready(function(){
    $('.slider').slider();
    });
  </script>

app/views/shared/_student_roster_card.html.erb
<% if logged_in?(:admin) %>
<div class="card amber accent-2">
  <div class="row">

        <h1>Morning Students</h1>
        <table>
        <thead>
            <tr>
            <th>Title</th>
            <th>Name</th>
            <th>Age</th>
            <th>Body</th>
            <th>Class Desired</th>
            <th>Timeslot</th>
            <th>Status</th>
            <th colspan="7"></th>
            </tr>
        </thead>

        <tbody>
        <% @mstudents.each do |post| if logged_in?(:admin) %>
            <% end %>
            <tr>
                <td><%= post.title %></td>
                <td><%= post.name %></td>
                <td><%= post.age %></td>
                <td><%= post.body %></td>
                <td><%= post.class_desired %></td>
                <td><%= post.timeslot %></td>
                <td><%= post.status %></td>
                <% end %>
        </tbody>

        </table>
        <h1>Afternoon Students</h1>
        <table>
        <thead>
            <tr>
            <th>Title</th>
            <th>Name</th>
            <th>Age</th>
            <th>Body</th>
            <th>Class Desired</th>
            <th>Timeslot</th>
            <th>Status</th>
            <th colspan="7"></th>
            </tr>
        </thead>

        <tbody>
        <% @astudents.each do |post| if logged_in?(:admin) %>
            <% end %>
            <tr>
                <td><%= post.title %></td>
                <td><%= post.name %></td>
                <td><%= post.age %></td>
                <td><%= post.body %></td>
                <td><%= post.class_desired %></td>
                <td><%= post.timeslot %></td>
                <td><%= post.status %></td>
                <% end %>
        </tbody>

        </table>

  </div>
</div>
<% end %>