config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :class_rosters do
    member do 
      get :toggle_status
    end 
  end

  resources :posts do 
    member do 
      get :toggle_status
      get :toggle_timeslot
    end 
  end 
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
resources 'users' do
  resources 'posts'
end 

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'schedule', to: 'pages#schedule'
  get 'payments', to: 'pages#payments'

  resources :blogs do 
    member do 
      get :toggle_status
    end 
  end

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :deposit, only: [:new, :create]
  get 'thank_you', to: 'deposit#thank_you', as: 'thank_you'
  root to: 'pages#home'
end

app/views/pages/about.html.erb
<h1>About the Teacher</h1><hr>
<%= render 'shared/about_card' %>
   
    <br>
    
    
   
<h1>What is unique about TLC Preschool?</h1><hr>

<p>
    Focus Points, Educational Standards
</p>
<%= render 'shared/focus_card' %>
    

app/views/pages/contact.html.erb
<h3>Contact info and Location of The Learning Center Preschool</h3>
<div class="row">
    <div class="col s6">
        <h4>Miss Betsy's Contact info</h4>
        <p>Located in Santaquin, Utah</p>
        <p>Home Phone: 801-754-1399, Cell: 385-404-9924 </p>
        <p><a href="mailto:elizabeth.montoya@aggiemail.usu.edu?subject=TheLearningCenter" "email me">Email the Teacher</a> </p>
        <p>Facebook: <a href="http://www.facebook.com/TheLearningCenterPreschool1" "facebook">The Learning Center Facebook</a> </p>
    </div>
    <div class="col s6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3057.662199899836!2d-111.77207434908757!3d39.97130459043129!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x874da8ae4e49a333%3A0x10a4e973e5691551!2s266+730+E%2C+Santaquin%2C+UT+84655!5e0!3m2!1sen!2sus!4v1512584672790" width="400" height="400" frameborder="2" style="border:1.5" allowfullscreen></iframe>
    </div>
</div>
<div class="row">
    <div class="col s12">
     <h6>Current students:</h6>
        <p>Things to look for...</p>
        <p>Email: Please check your email often, including your spam box.</p> 
        <p>Group me App: I will use this app to send out quick messages and reminders. </p> 
        <p>Parent Postcard: Each day your child will come home with a parent postcard. This is a summary of what we did in preschool that day. This helps you to talk with them about what we learned and ask them about their day at preschool!</p>
        <p>Homework Heroes: Most days, on the bottom of the parent postcard, there is a homework hero activity. This is a simple activity for you to do with your child that will reinforce what we learn each day!</p>
    </div>
</div>    

app/views/pages/home.html.erb
<blockquote><h2>Hi, <%= current_user.first_name %>, Welcome to The Learning Center!</h2></blockquote>
<hr>
<%= link_to "CHOICE | Registration", posts_path %>
|
<%= link_to "CHOICE | Tuition", new_charge_path %>
<%= link_to "Admin Dashboard", admin_root_path %>
|
<%= link_to "CHOICE | Class of 2018", class_rosters_path %>
<%= render 'shared/home_card' %>
<%= render 'shared/home_carousel' %>
<hr>

app/views/pages/payments.html.erb
<h1>Tuition Payments</h1>
<%# <p>The material fee is a one time payment of $50.00, any other monies owed can be paid through here as well.</p> %>
<p>The Tuition payment form is set to the amount of $65.00, this is due monthly. Thanks!</p>
<hr>
<%# <%= link_to 'Material Fee Deposit', new_deposit_path %> 
<%# <a class="btn-floating btn-large waves-effect waves-light green" href="/deposit/new"><i class="material-icons">payment</i></a> %>
<%# <br> %>
<%= link_to 'Monthly Tuition', new_charge_path %>
<a class="btn-floating btn-large waves-effect waves-light green darken-2" href="/charges/new"><i class="material-icons">class</i></a>

app/views/pages/schedule.html.erb
<h1>The Learning Center Schedules</h1>
<h3>Morning Activity Schedule</h3>
    <hr>
    <table class="striped">
        <thead>
          <tr>
              <th>Time</th>
              <th>Activity</th>
              <th>Description</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>9:15- 10:00</td>
            <td>Free Play</td>
            <td>Toys, block, dolls and the like make this a fun time for children. I also work with children individually for a few minutes of this time to develop skills. This time is an essential part of our day!</td>
          </tr>
          <tr>
            <td>10:00-10:20</td>
            <td>Circle time</td>
            <td>This is our large group time. We sit around the circle and talk, sing play games and learn about the theme for the day as well as literacy activities. We each get to sit on a soft pillow!</td>
          </tr>
          <tr>
            <td>10:20-10:30</td>
            <td>Music and Movement</td>
            <td>We sing, dance and move all around.</td>
          </tr>
          <tr>
            <td>10:30-10:45</td>
            <td>Art Time</td>
            <td>Fun, creative and usually original, sometimes messy art!</td>
          </tr>
          <tr>
            <td>10:45-11:00</td>
            <td>Snack time.</td>
            <td>We sit down to have a snack and renew our energy. We build social skills, too!</td>
          </tr>
          <tr>
            <td>11:00-11:30</td>
            <td>Centers.</td>
            <td>We divide up into small groups and go to different center activities that cover a broad range of learning. This is usually the children’s favorite time!</td>
          </tr>
          <tr>
            <td>11:30-11:45</td>
            <td>Clean Up</td>
            <td> Pack up and closing circle.</td>
          </tr>
        </tbody>
      </table>

    <h3>Afternoon Activity Schedule</h3><hr>
    <table class="striped">
        <thead>
          <tr>
              <th>Time</th>
              <th>Activity</th>
              <th>Description</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>12:30-1:15 PM</td>
            <td>Free Play</td>
            <td>Toys, block, dolls and the like make this a fun time for children. I also work with children individually for a few minutes of this time to develop skills. This time is an essential part of our day!</td>
          </tr>
          <tr>
            <td>1:15-1:30 PM</td>
            <td>Circle time</td>
            <td>This is our large group time. We sit around the circle and talk, sing play games and learn about the theme for the day as well as literacy activities. We each get to sit on a soft pillow!</td>
          </tr>
          <tr>
            <td>1:30-1:40 PM</td>
            <td>Music and Movement</td>
            <td>We sing, dance and move all around.</td>
          </tr>
          <tr>
            <td>1:40-1:55 PM</td>
            <td>Art Time</td>
            <td>Fun, creative and usually original, sometimes messy art!</td>
          </tr>
          <tr>
            <td>1:55-2:10 PM</td>
            <td>Snack time.</td>
            <td>We sit down to have a snack and renew our energy. We build social skills, too!</td>
          </tr>
          <tr>
            <td>2:10-2:40 PM</td>
            <td>Centers.</td>
            <td>We divide up into small groups and go to different center activities that cover a broad range of learning. This is usually the children’s favorite time!</td>
          </tr>
          <tr>
            <td>2:40-3:00 PM</td>
            <td>Clean Up</td>
            <td> Pack up and closing circle.</td>
          </tr>
        </tbody>
      </table>