config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :class_rosters do
    member do 
      get :toggle_status
    end 
  end

  resources :posts do 
    member do 
      get :toggle_status
      get :toggle_timeslot
    end 
  end 
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
resources 'users' do
  resources 'posts'
end 

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'schedule', to: 'pages#schedule'
  get 'payments', to: 'pages#payments'

  resources :blogs do 
    member do 
      get :toggle_status
    end 
  end

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :deposit, only: [:new, :create]
  get 'thank_you', to: 'deposit#thank_you', as: 'thank_you'
  root to: 'pages#home'
end

app/models/post.rb
class Post < ApplicationRecord
    enum status: { pending: 0, approved: 1 }
    enum gender: { male: 0, female: 1 }
    enum timeslot: { morning: 0, afternoon: 1 }
    extend FriendlyId
    friendly_id :title, use:  :slugged 

    validates_presence_of :title, :name, :age, :body, :class_desired, :gender
    belongs_to :user
    belongs_to :class_roster
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_status, :toggle_timeslot]
  access all: [:show, :index, :new, :create], user: {except: [:destroy, :update, :edit, :toggle_status, :toggle_timeslot]}, admin: :all

  # GET /posts
  def index
    if logged_in?(:admin)
    @posts = Post.all
  else 
    @posts = Post.approved
  end
    @page_title = "TLC Registration"
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def toggle_status
    if @post.pending?
      @post.approved!
    elsif @post.approved?
      @post.pending!
    end 
    redirect_to posts_url, notice: 'Post has been updated'
  end 
  
  def toggle_timeslot
    if @post.morning?
      @post.afternoon!
    elsif @post.afternoon?
      @post.morning!
    end 
    redirect_to posts_url, notice: 'Post has been updated'
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :name, :age, :body, :class_desired, :gender)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
  <% post.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "TLC Posts") %>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :post_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :post_age %>
  </div>


<div class="field">
    <input name="post[class_desired]" class="with-gap" type="radio" id="class_desired_id" value="afternoon">
    <label for="class_desired_id" value="afternoon">Afternoon</label>
</div>

<div class="field">
    <input name="post[class_desired]" class="with-gap" type="radio" id="class_desired_id_green" value="morning">
    <label for="class_desired_id_green" value="morning">Morning</label>
</div>

  <div class="field">
      <input name="post[gender]" class="with-gap" type="radio" id="gender_id" value="male">
      <label for="gender_id" value="male">Male</label>
    </div>

    <div class="field">
      <input name="post[gender]" class="with-gap" type="radio" id="gender_id_yellow" value="female">
      <label for="gender_id_yellow" value="female">Female</label>
    </div>

  <div class="field">
    <%= form.label :class_desired_because %>
    <%= form.text_area :body, id: :post_body %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
$(document).ready(function() {
  $('select').material_select();
});
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag "_header.png" %>

<h1>Student Posts</h1>
<p>Once you decide which class time will work best for you sign up your child and post a class schedule request!</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>Age</th>
      <th>Body</th>
      <th>Class Desired</th>
      <th>Timeslot</th>
      <th>Status</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| if logged_in?(:admin) %>
    <% end %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.name %></td>
        <td><%= post.age %></td>
        <td><%= post.body %></td>
        <td><%= post.class_desired %></td>
        <td><%= link_to post.timeslot, toggle_timeslot_post_path(post) %></td>
        <td><%= link_to post.status, toggle_status_post_path(post) %></td>
        <td><%= link_to(edit_post_path(post), :id => :post, class: "btn-floating yellow darken-1") do %>
              <i class='material-icons'>edit</i><% end %></td>
        <td><%= link_to(post_path(post), :id => :post, class: "btn-floating green") do %><i class="material-icons">assignment_return</i><% end %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:admin) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<a class="btn-floating btn-large waves-effect waves-light red" href="/posts/new"><i class="material-icons">class</i></a></a>

<%= link_to 'Back', root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @post.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @post.gender %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Class desired:</strong>
  <%= @post.class_desired %>
</p>

<p>
  <strong>Timeslot:</strong>
  <%= @post.timeslot %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>